### PR TITLE
Bug fixes

### LINKED ISSUE #723: Session user name disappear on the old device when link a new device
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

This might be a regression, not sure when it starts. Reproducible on both Session iOS 2.2.0 and Session iOS 2.2.1.

**To reproduce**

Old device: Session Desktop / Session iOS
New device: Session iOS

Steps:

1. create a fresh new Session ID on an old device with the user name "Test"
2. "Link a device" from the new device to the old device

Expect result:
Both old device and new device has the same user name "Test"

Actual result:
Old device has no user name anymore, not sure if it's an empty string or a NULL pointer.
New device has the correct user name "Test"
Edit: after syncing for a while, new device lost its user name as well.

It seems impossible to edit the user name on the old device anymore, the user name input box on the old device is non-editable after linking the new device.

Session user name

You can also tell from the Avatar placeholder, it's no longer an abbreviate of user name, it becomes completely empty.

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone SE, iPad
 - OS: iOS 15.6
 - Version of Session: 2.2.0 / 2.2.1

**Additional context**

We need better test cases to cover this kind of weird edge case :D

### PR DESCRIPTION
**Pull request by RyanRory**
- Fix open group messages trimming
- Fix #723 
- Fix the crash in #715

### CODE REVIEW

**Review by mpretty-cyro — APPROVED** [review]

**Review by ianmacd — CHANGES_REQUESTED** [review]
It looks as if this will **still** reject seed lengths other than 16 bytes.

This is at odds with both the Desktop and Android clients, both of which are quite happy to accept longer seed lengths.

**Comment by ianmacd** [comment]
Again, this doesn't look as if it actually fixes #715. It will stop the crash, but it still won't allow the longer recovery phrase, which is at odds with the desktop and Android clients' handling of the situation.

**Comment by mpretty-cyro** [comment]
> Again, this doesn't look as if it actually fixes #715. It will stop the crash, but it still won't allow the longer recovery phrase, which is at odds with the desktop and Android clients' handling of the situation.

This PR wasn't intended to fix #715, just fix the crash in the interim (and as such the issue is still open)

**Comment by fracting** [comment]
Hi @RyanRory @mpretty-cyro did you see my updates on https://github.com/oxen-io/session-ios/issues/723?

**Comment by mpretty-cyro** [comment]
> Hi @RyanRory @mpretty-cyro did you see my updates on #723?

Thanks for updating the issue, I've added a response on #723 -  it's a shame it hasn't been filly fixed as part of this but #751 replaces the old user info syncing mechanism with a much more hardy one that shouldn't have issues like this

**Pull request merged**
